version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.7.0
    
    working_directory: ~/

    steps:
      - checkout
      - run: npm --version
  test:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.7.0

    working_directory: ~/

    steps:
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build