version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.7.0
    
    steps:
      - checkout
      - run: 
        - name: Version Checks
        - run: |
            npm --version
            echo $ANDROID_SDK_HOME
            echo $ANDROID_HOME
            xcrun simctl list
      - run:
        - name: Install Depedencies
        - run: |
            npm install --save-dev


  test:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.7.0

    steps:
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build